local opt = vim.opt

opt.cursorline = true
opt.signcolumn = "yes"
opt.tabstop = 4
opt.softtabstop = 4
opt.shiftwidth = 4
opt.expandtab = true
opt.ignorecase = true
opt.smartcase = true
opt.smartindent = true
opt.hlsearch = true
opt.incsearch = true
opt.number = true
opt.relativenumber = true
opt.hidden = true
opt.grepprg = "rg --vimgrep"
opt.clipboard = "unnamedplus"
opt.pumheight = 20
opt.foldlevel = 99
opt.belloff = "all"
opt.linebreak = true
opt.matchtime = 0
opt.showmatch = true
opt.showmode = false
opt.splitbelow = true
opt.splitright = true
opt.termguicolors = true
opt.undofile = true
opt.updatetime = 1000
opt.wrap = false
opt.pumblend = 10
opt.winblend = 10
